### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [smuehlst/longan-nano-experiments#1]
Hello!

I found this project from https://sigmdel.ca/michel/ha/gd32v/longan_nano_01_en.html#hello

Could you please add information about the license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by smuehlst** [comment]
Added a LICENSE file.

**Comment by vazhnov** [comment]
Unlicense — cool!
Thank you!
